name: pemd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - gmso=0.12.0
  - openbabel=3.1.1
  - numpy
  - pandas
  - scipy=1.12.0
  - xtb=6.6.1
  - packmol=20.010
  - pip:
      - requests
